- name: Create Livepeer Directories
  tags: livepeer
  ansible.builtin.file:
    mode: '700'
    path: /home/jason/.lpData/arbitrum-one-mainnet/keystore
    state: directory
    owner: jason
    group: jason
    recurse: true

- name: Copy Ethereum Wallet to Livepeer
  tags: livepeer
  ansible.builtin.copy:
    src: files/UTC--2016-03-12T21-58-48.509345400Z--74ba897f65f04008d8eff364efcc54b0a20e17eb
    dest: /home/jason/.lpData/arbitrum-one-mainnet/keystore/UTC--2016-03-12T21-58-48.509345400Z--74ba897f65f04008d8eff364efcc54b0a20e17eb
    mode: '0600'
    owner: jason
    group: jason

# note: this requires the host to have the nvenv nvidia patch if it is a consumer
# nvidia card: https://github.com/keylase/nvidia-patch
- name: Deploy Livepeer Transcoder with Nvidia GPU
  tags: livepeer
  vars:
    ansible_python_interpreter: "/usr/bin/env python3-docker"
  community.docker.docker_container:
    name: livepeer
    image: livepeer/go-livepeer:0.5.28-71267f44
    pull: true
    restart_policy: unless-stopped
    device_requests:
      - driver: nvidia
        count: -1
        capabilities:
          - gpu
    command: >
      -transcoder -nvidia 0 -orchSecret {{ orchSecret }} -orchAddr lp.jasonernst.com:8935 -monitor --cliAddr 0.0.0.0:7935
    network_mode: host
    volumes:
      - "/home/jason/.lpData:/root/.lpData"
