---
galaxy_info:
  author: Kai (via compscidr/iac)
  description: Install and configure Stalwart Mail Server
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble

dependencies:
  - common_cli
