# https://github.com/google/android-emulator-container-scripts
- name: Deploy Android Emulator
  tags: android-emulator, gh-actions
  vars:
    ansible_python_interpreter: "/usr/bin/env python3-docker"
  docker_container:
    name: android-emulator-grape
    image: us-docker.pkg.dev/android-emulator-268719/images/30-google-x64:latest
    pull: true
    restart_policy: unless-stopped
    devices:
      - "/dev/kvm"
    ports:
      - "5555"
    env:
      EMULATOR_ARGS: "-gpu swiftshader_indirect"

# https://github.com/myoung34/docker-github-actions-runner
- name: Deploy Github Actions Runner
  tags: gh-actions
  vars:
    ansible_python_interpreter: "/usr/bin/env python3-docker"
  docker_container:
    name: grape-gh-actions
    image: myoung34/github-runner:latest
    pull: true
    volumes:
      - "/dev/bus/usb:/dev/bus/usb"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart_policy: unless-stopped
    privileged: true
    env:
      ACCESS_TOKEN: "{{ gh_pat }}"
      RUNNER_NAME_PREFIX: grape
      RUNNER_WORKDIR: /tmp/grape
      RUNNER_GROUP: default
      REPO_URL: https://github.com/compscidr/grape-networking-java
      LABELS: "self-hosted"
      RUNNER_SCOPE: "org"
      ORG_NAME: "grape-networking"
    links:
      - "android-emulator-grape"

# https://github.com/google/android-emulator-container-scripts
- name: Deploy Android Emulator
  tags: android-emulator, gh-actions
  vars:
    ansible_python_interpreter: "/usr/bin/env python3-docker"
  docker_container:
    name: android-emulator-hello-java
    image: us-docker.pkg.dev/android-emulator-268719/images/30-google-x64:latest
    pull: true
    restart_policy: unless-stopped
    devices:
      - "/dev/kvm"
    ports:
      - "5555"
    env:
      EMULATOR_ARGS: "-gpu swiftshader_indirect"

- name: Deploy Github Actions individual repo runners
  tags: gh-actions
  vars:
    ansible_python_interpreter: "/usr/bin/env python3-docker"
  docker_container:
    name: "{{ item.name }}"
    image: myoung34/github-runner:latest
    pull: true
    volumes:
      - "/dev/bus/usb:/dev/bus/usb"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart_policy: unless-stopped
    privileged: true
    env:
      ACCESS_TOKEN: "{{ gh_pat }}"
      RUNNER_NAME_PREFIX: "{{ item.name }}"
      RUNNER_WORKDIR: "/tmp/{{ item.name }}"
      RUNNER_GROUP: default
      REPO_URL: "https://github.com/{{ item.repo }}"
      LABELS: "self-hosted"
    links:
      - "android-emulator-hello-java"
  loop:
    - { name: 'hello-java-android', repo: 'compscidr/hello-java-android' }  # noqa yaml
