# Platform-specific package definitions

# Android tools
dev_android_packages_ubuntu:
  - adb
  - android-sdk-platform-tools-common

dev_android_packages_macos:
  - android-platform-tools

# Java
dev_java_packages_ubuntu:
  - openjdk-21-jdk-headless

dev_java_packages_macos:
  - openjdk@21

# C++ Development
dev_cpp_packages_ubuntu:
  - build-essential
  - cmake
  - autoconf
  - strace
  - ltrace
  - valgrind
  - hotspot
  - heaptrack
  - clang-format
  - clang-tidy
  - pkg-config

dev_cpp_packages_macos:
  - cmake
  - autoconf
  - pkg-config
  - llvm

# Golang
dev_golang_packages_ubuntu:
  - golang

dev_golang_packages_macos:
  - go

# Node.js
dev_node_packages_ubuntu:
  - npm

dev_node_packages_macos:
  - node

# Python
dev_python_packages_ubuntu:
  - python3-dev
  - python3-pip
  - python3-venv
  - python3-setuptools
  - python-is-python3
  - python3-poetry
  - python3-passlib
  - pipx

dev_python_packages_macos:
  - python@3.12

# Rust
dev_rust_packages_ubuntu:
  - rustc
  - cargo

dev_rust_packages_macos:
  - rust

# Ruby
dev_ruby_packages_ubuntu:
  - ruby-full

dev_ruby_packages_macos:
  - ruby

# HashiCorp
dev_hashicorp_packages_ubuntu:
  - vagrant
  - terraform
  - packer

dev_hashicorp_packages_macos:
  - hashicorp/tap/terraform
  - hashicorp/tap/packer
  # Note: Vagrant excluded - installer hangs via Homebrew on macOS
  # TODO: Move to GUI dev tools role and install via official DMG from vagrantup.com

# Cloud CLIs
dev_cloud_packages_macos:
  - awscli
  - doctl

# Network/Misc tools
dev_misc_packages_macos:
  - zig

# Tailscale
dev_tailscale_packages_ubuntu:
  - tailscale

dev_tailscale_packages_macos:
  - tailscale

# PHP (Ubuntu/Debian only - uses geerlingguy role)
php_memory_limit: "128M"
php_max_execution_time: "90"
php_upload_max_filesize: "256M"
php_default_version_debian: "8.3"
php_packages:
  - "php{{ php_default_version_debian }}"
  - "php{{ php_default_version_debian }}-cli"
  - "php{{ php_default_version_debian }}-common"
  - "php{{ php_default_version_debian }}-curl"
  - "php{{ php_default_version_debian }}-dev"
  - "php{{ php_default_version_debian }}-gd"
  - "php{{ php_default_version_debian }}-mbstring"
  - "php{{ php_default_version_debian }}-sqlite3"
  - "php{{ php_default_version_debian }}-xml"
  - "php{{ php_default_version_debian }}-intl"
