# https://gist.github.com/drmalex07/c0f9304deea566842490
- name: Copy Secure Tunnel Service File
  become: true
  tags: livepeer
  ansible.builtin.copy:
    src: files/secure-tunnel@.service
    dest: /etc/systemd/system/secure-tunnel@.service
    mode: '0600'

# note: for this to work the first time, you'll need to do an ssh first and
# accept the key
- name: Copy Ethereum API Tunnel
  become: true
  tags: livepeer
  ansible.builtin.copy:
    src: files/secure-tunnel@ubuntu-desktop-beast
    dest: /etc/default/secure-tunnel@ubuntu-desktop-beast
    mode: '0644'

- name: Enable Secure-Tunnel Ethereum
  become: true
  tags: livepeer
  ansible.builtin.systemd:
    name: secure-tunnel@ubuntu-desktop-beast
    enabled: true
    state: started
    masked: false

# note: for this to work the first time, you'll need to do an ssh first and
# accept the key
- name: Copy Arbitrum API Tunnel
  become: true
  tags: livepeer
  ansible.builtin.copy:
    src: files/secure-tunnel@ubuntu-desktop-beast-arbitrum
    dest: /etc/default/secure-tunnel@ubuntu-desktop-beast-arbitrum
    mode: '0644'

- name: Enable Secure-Tunnel Arbitrum
  become: true
  tags: livepeer
  ansible.builtin.systemd:
    name: secure-tunnel@ubuntu-desktop-beast-arbitrum
    enabled: true
    state: started
    masked: false

- name: Create Livepeer Directories
  tags: livepeer
  ansible.builtin.file:
    mode: '700'
    path: /home/jason/.lpData/arbitrum-one-mainnet/keystore
    state: directory
    owner: jason
    group: jason
    recurse: true

- name: Copy Ethereum Wallet to Livepeer
  tags: livepeer
  ansible.builtin.copy:
    src: files/UTC--2016-03-12T21-58-48.509345400Z--74ba897f65f04008d8eff364efcc54b0a20e17eb
    dest: /home/jason/.lpData/arbitrum-one-mainnet/keystore/UTC--2016-03-12T21-58-48.509345400Z--74ba897f65f04008d8eff364efcc54b0a20e17eb
    mode: '0600'
    owner: jason
    group: jason

# note: can't run as both transcoder and orchestrator at same time
# if you want to use orch secret and allow other transcoders to register
# also note: if the price per pixel > 1200 the perf test won't run
- name: Deploy Livepeer Orchestrator
  tags: livepeer
  vars:
    ansible_python_interpreter: "/usr/bin/env python3-docker"
  community.docker.docker_container:
    name: livepeer
    image: livepeer/go-livepeer:0.5.30-dd41f107
    pull: true
    restart_policy: unless-stopped
    command: >
      -network arbitrum-one-mainnet -ethUrl {{ alchmey_url }} -ethAcctAddr 0x74ba897f65f04008d8eff364efcc54b0a20e17eb -orchestrator -pricePerUnit 995
      -pixelsPerUnit 1 -autoAdjustPrice=false -serviceAddr lp.jasonernst.com:8935 -reward=true -orchSecret {{ orchSecret }}
      -ethPassword {{ ethPassword }} -monitor -cliAddr 0.0.0.0:7935 -blockPollingInterval 8
    volumes:
      - "/home/jason/.lpData:/root/.lpData"
    network_mode: host
