# https://github.com/compscidr/docker-github-actions-runner-android
- name: Deploy GH actions for bump
  tags: gh-actions
  vars:
    ansible_python_interpreter: "/usr/bin/env python3-docker"
  docker_container:
    name: bump-gh-actions-jvm
    image: compscidr/github-runner-android:latest
    pull: true
    volumes:
      - "/dev/bus/usb:/dev/bus/usb"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart_policy: unless-stopped
    privileged: true
    env:
      ACCESS_TOKEN: "{{ gh_pat }}"
      DISABLE_AUTO_UPDATE: "true"
      RUNNER_NAME_PREFIX: "bump-jvm"
      RUNNER_WORKDIR: /tmp/bump
      RUNNER_GROUP: default
      REPO_URL: https://github.com/BumpApp/hop-poc
      LABELS: "jvm"
      RUNNER_SCOPE: "org"
      ORG_NAME: "BumpApp"
