---
# Ollama role handlers

- name: Restart Docker
  become: true
  ansible.builtin.systemd:
    name: docker
    state: restarted

- name: Restart Ollama
  become: true
  community.docker.docker_compose_v2:
    project_src: "{{ ollama_data_path }}"
    state: restarted
