# External Ansible Dependencies
#
# This file defines external roles and collections from Ansible Galaxy.
#
# INSTALLATION:
#   - For Molecule: Automatic (via dependency.sh script)
#   - For Standalone: Run 'ansible-galaxy install -r requirements.yml'
#
# See DEPENDENCIES.md for more information.

roles:
  - name: compscidr.gpg
    version: "0.0.12"
  - name: webarchitect609.jet_brains_toolbox
    version: "3.0.0"
  - name: geerlingguy.php
    version: "6.0.0"
  - name: compscidr.lapce
    version: "0.0.3"
  - name: luizgavalda.gnome_extensions

collections:
  - name: ansible.posix
  - name: community.general
    version: "12.4.0"
  - name: community.docker
    version: "5.0.5"
  - name: compscidr.media_server
    version: "1.3.1"
  - name: compscidr.github_runner
    version: "0.1.2"
  - name: compscidr.rust_gameserver
    version: "0.0.6"
  - name: compscidr.github_cli
    version: "0.0.16"
  - name: compscidr.onepassword
    version: "0.1.2"
  - name: compscidr.spotify
    version: "0.0.4"
  - name: compscidr.keybase
    version: "0.0.1"
